spring.application.name=rajaayam

spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}

server.port=${PORT:8080}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true