spring.application.name=rajaayam

spring.datasource.url=jdbc:mysql://acela.proxy.rlwy.net:53830/railway
spring.datasource.username=root
spring.datasource.password=kQbJoFNiHCDuESFXJrwYmuJWAWCuUYos

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true