spring.datasource.url=jdbc:mysql://acela.proxy.rlwy.net:53830/railway
spring.datasource.username=root
spring.datasource.password=kQbJoFNiHCDuESFXJrwYmuJWAWCuUYos

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=${PORT:8080}